spring.application.name=party-manager
# 1. Habilita a interface visual do banco no navegador
spring.h2.console.enabled=true

# 2. Define o endereço da interface (localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# 3. Configura o banco para rodar na memória (rápido e leve)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# 4. Faz o Hibernate criar as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update